---
title: "Digital Signature"
author: "Antonio Canepa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Images for digital signature

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
```


```{r}
n = 500
t1 = 1:n
t0 = seq(from = 0, by = 102,length.out = n) %% n
tibble(x = cos((t1 - 1)*2*pi/n),y = sin((t1 - 1)*2*pi/n), 
       z = cos((t0 - 1)*2*pi/n), w = sin((t0 - 1)*2*pi/n)) %>% 
  ggplot(aes(x = x, y = y, xend = z, yend = w)) +
  geom_segment(alpha = .2) + coord_equal() + theme_void()
```

```{r, purl=FALSE, eval=FALSE}
# run only to export the plot
n = 500
t1 = 1:n
t0 = seq(from = 0, by = 102,length.out = n) %% n
tibble(x = cos((t1 - 1)*2*pi/n),y = sin((t1 - 1)*2*pi/n), 
       z = cos((t0 - 1)*2*pi/n), w = sin((t0 - 1)*2*pi/n)) %>% 
  ggplot(aes(x = x, y = y, xend = z, yend = w)) +
  geom_segment(alpha = .2) + coord_equal() + theme_void() -> P1
```


```{r, purl=FALSE, eval=FALSE}
ggsave(filename ='Circle.png' , plot = P1, path = paste(getwd(), "/Images", sep = ""), scale = , width = 5, height = 5, units = "cm", dpi = 300)
```
