---
title: "Digital Signature"
author: "Antonio Canepa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Images for digital signature

```{r, warning=FALSE, message=FALSE}
#remotes::install_github("djnavarro/jasmines")
library(jasmines)
library(tidyverse)
```


```{r}
use_seed(1) %>%
  scene_discs(
    rings = 3, points = 5000, size = 5
  ) %>%
  mutate(ind = 1:n()) %>%
  unfold_warp(
    iterations = 1,
    scale = .5, 
    output = "layer" 
  ) %>%
  unfold_tempest(
    iterations = 20,
    scale = .01
  ) %>%
  style_ribbon(
    palette = palette_named("vik"),
    colour = "ind",
    alpha = c(.1,.1),
    background = "white"
  )
```
```{r, purl=FALSE, eval=FALSE}
# run only to export the plot
use_seed(1) %>%
  scene_discs(
    rings = 3, points = 5000, size = 5
  ) %>%
  mutate(ind = 1:n()) %>%
  unfold_warp(
    iterations = 1,
    scale = .5, 
    output = "layer" 
  ) %>%
  unfold_tempest(
    iterations = 20,
    scale = .01
  ) %>%
  style_ribbon(
    palette = palette_named("vik"),
    colour = "ind",
    alpha = c(.1,.1),
    background = "white"
  ) -> P1
```


```{r, purl=FALSE, eval=FALSE}
ggsave(filename ='Fluid.png' , plot = P1, path = paste(getwd(), "/Images", sep = ""), scale = , width = 5, height = 5, units = "cm", dpi = 300)
```
