---
title: "Digital Signature"
author: "Antonio Canepa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Images for digital signature

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
```

### Black and white

```{r}
seq(from = -10, to = 10, by = 0.025) %>%
  expand.grid(x = ., y = .) %>%
  ggplot(aes(y = (y + pi*abs(cos(x))^.5), x = (x + pi*abs(sin(y))^.5))) +
  geom_point(alpha = .01, shape = 20, size = 0, color = "black") +
  theme_void() + 
  coord_fixed() +
  theme(legend.position = "none")
```

```{r, purl=FALSE, eval=FALSE}
# run only to export the plot
seq(from = -10, to = 10, by = 0.025) %>%
  expand.grid(x = ., y = .) %>%
  ggplot(aes(y = (y + pi*abs(cos(x))^.5), x = (x + pi*abs(sin(y))^.5))) +
  geom_point(alpha = .01, shape = 20, size = 0, color = "black") +
  theme_void() + 
  coord_fixed() -> P1
```


```{r, purl=FALSE, eval=FALSE}
ggsave(filename ='Waves.png' , plot = P1, path = paste(getwd(), "/Images", sep = ""), scale = , width = 5, height = 5, units = "cm", dpi = 300)
```

### Coloured version
```{r}
seq(from = -10, to = 10, by = 0.025) %>%
  expand.grid(x = ., y = .) %>%
  ggplot(aes(y = (y + pi*abs(cos(x))^.5), x = (x + pi*abs(sin(y))^.5))) +
  geom_point(alpha = .01, shape = 20, size = 0, aes(colour = x + pi*abs(sin(y)))) +
  theme_void() + 
  coord_fixed() +
  theme(legend.position = "none")
```

```{r, purl=FALSE, eval=FALSE}
# run only to export the plot
seq(from = -10, to = 10, by = 0.025) %>%
  expand.grid(x = ., y = .) %>%
  ggplot(aes(y = (y + pi*abs(cos(x))^.5), x = (x + pi*abs(sin(y))^.5))) +
  geom_point(alpha = .01, shape = 20, size = 0, aes(colour = x + pi*abs(sin(y)))) +
  theme_void() + 
  coord_fixed() +
  theme(legend.position = "none") -> P2
```


```{r, purl=FALSE, eval=FALSE}
ggsave(filename ='Waves_coloured.png' , plot = P2, path = paste(getwd(), "/Images", sep = ""), scale = , width = 5, height = 5, units = "cm", dpi = 300)
```
